name = "remix-cloudflare-example"
compatibility_date = "2024-03-20"

# Bind a D1 database. D1 is Cloudflare’s native serverless SQL database.
# Docs: https://developers.cloudflare.com/pages/functions/bindings/#d1-databases
[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "remix-cloudflare-example"
database_id = "a85981b6-98b1-4ddf-ab63-0af63e0e1e32"
